# NexQuake (nqwasm) Makefile for Emscripten / WebAssembly
# Written by Gregory Maynard-Hoare

ifeq ($(NEXQUAKE_VERSION),)
	NEXQUAKE_VERSION := $(shell cat VERSION 2>/dev/null || git describe --tags --always --dirty 2>/dev/null || echo unknown)
endif

# Compiler / linker parameters
CC := emcc
CFLAGS := -std=gnu11 -O3 -ffast-math -funroll-loops -fomit-frame-pointer -Wall -Wextra -Wno-implicit-function-declaration \
	-Wno-unused-parameter -Wno-missing-field-initializers -Wno-sign-compare -Wno-pointer-sign \
	-DNEXQUAKE_VERSION='"$(NEXQUAKE_VERSION)"'
WEBSOCKET_URL_FLAG :=
ifneq ($(strip $(WEBSOCKET_URL)),)
WEBSOCKET_URL_FLAG := -sWEBSOCKET_URL=$(WEBSOCKET_URL)
endif
SEED_PRELOAD_FLAGS := --preload-file seed@/nqseed
LDFLAGS := -O3 -Wl,--allow-multiple-definition -sMAX_WEBGL_VERSION=2 -sMIN_WEBGL_VERSION=2 -sINITIAL_MEMORY=64MB -sTOTAL_STACK=2MB -sALLOW_MEMORY_GROWTH \
	$(SEED_PRELOAD_FLAGS) \
	--shell-file shell.html --pre-js nq-pre.js -lidbfs.js $(WEBSOCKET_URL_FLAG) -sWEBSOCKET_SUBPROTOCOL=binary \
	-lwebsocket.js -sASYNCIFY=1 -sASYNCIFY_STACK_SIZE=4MB -sASYNCIFY_IGNORE_INDIRECT=0 -sALLOW_BLOCKING_ON_MAIN_THREAD=1 \
	-sEXPORTED_RUNTIME_METHODS=['addRunDependency','removeRunDependency','ccall','callMain'] -sEXPORT_KEEPALIVE=1
TARGET := index.html

# C source files
SRCS := \
chase.c \
cl_demo.c \
cl_input.c \
cl_main.c \
cl_parse.c \
cl_tent.c \
cmd.c \
common.c \
console.c \
crc.c \
cvar.c \
host.c \
host_cmd.c \
keys.c \
mathlib.c \
menu.c \
net_bsd.c \
net_dgrm.c \
net_loop.c \
net_main.c \
net_slist.c \
net_vcr.c \
net_ws_transport.c \
net_ws_vnet.c \
cmd_rcon.c \
com_gameswitch.c \
cl_prefetch.c \
pr_cmds.c \
pr_edict.c \
pr_exec.c \
r_part.c \
sbar.c \
snd_dma.c \
snd_mem.c \
snd_mix.c \
sv_main.c \
sv_move.c \
sv_phys.c \
sv_user.c \
view.c \
wad.c \
world.c \
zone.c

SRCS += \
d_edge.c \
d_fill.c \
d_init.c \
d_modech.c \
d_part.c \
d_polyse.c \
d_scan.c \
d_sky.c \
d_sprite.c \
d_surf.c \
d_vars.c \
d_zpoint.c \
draw.c \
model.c \
nonintel.c \
r_aclip.c \
r_alias.c \
r_bsp.c \
r_draw.c \
r_edge.c \
r_efrag.c \
r_light.c \
r_main.c \
r_misc.c \
r_sky.c \
r_sprite.c \
r_surf.c \
r_vars.c \
screen.c

SRCS += \
cd_wasm.c \
in_wasm.c \
sys_wasm.c \
vid_wasm.c \
snd_wasm.c

OBJS := $(SRCS:.c=.o)

.PHONY: all clean

all: $(TARGET)

# Link object files and create executable
$(TARGET): $(OBJS)
	$(CC) $^ $(LDFLAGS) -o $@

# Build object files from source
%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

# Remove object files and executable upon request
clean:
	rm -f $(OBJS) $(TARGET) index.data index.js index.wasm
